adding rotation modifier for gestures
adafruit/Adafruit_CircuitPython_APDS9960 pull request #26
Opened 2020-05-04 23:37 UTC by FoamyGuy

This adds a rotation offset that can be used to adjust the values returned by `gesture()` in case your sensor is mounted in a different orientation.

2020-06-10 10:13 UTC, jerryneedell commented on adafruit_apds9960/apds9960.py
> +
I think this should throw a ValueError if the input is not in [0,90,180,270] - it will just ignore it silently as written

2020-06-10 10:14 UTC, jerryneedell requested changes
Nice additions! This works well - tested with an apds9960_breakout on a grandcentral_m4.
I think it should be made clear that only values of 0,90,180,270 are permitted and throw an error (ValueError) if something else is input. A note should also be added to the Doc String that only these 4 values are accepted.

2020-06-10 10:17 UTC, jerryneedell commented on adafruit_apds9960/apds9960.py
> +        return self._rotation
Indicate that only [0,90,180,270] are acceptable

2020-06-10 14:47 UTC, FoamyGuy commented
Agree'd thank you for catching that @jerryneedell. I will make those changes later on tonight.

2020-06-13 09:41 UTC, jerryneedell commented on adafruit_apds9960/apds9960.py
> +
Thanks

2020-06-13 09:41 UTC, jerryneedell approved these changes
Looks good to me - tested with breakout on grandcentral. Entered 100 -- received ValueError

2020-06-17 23:25 UTC, merged